### PR TITLE
svelte-based visualize sidebar

### PR DESCRIPTION
**Pull request by gka**
Related PRs:
* https://github.com/datawrapper/plugin-tables/pull/42
* https://github.com/datawrapper/plugin-d3-lines/pull/48
* https://github.com/datawrapper/plugin-options/pull/6
* https://github.com/datawrapper/plugin-d3-bars/pull/68
* https://github.com/datawrapper/plugin-d3-scatter-plot/pull/14

### CODE REVIEW

**Comment by sjockers** [comment]
@gka Could you try to merge `master` back into this branch? I'd like to deploy it to a dev environment but it has diverged from master quite a bit. I tried it myself but struggled to make sense of the conflicts in `www/static/js/dw/chart/visualize.js`.

**Comment by gka** [comment]
fyi: I think this should also happen in the new visualize step: https://github.com/datawrapper/datawrapper/commit/b94e3d661ae5535e25dfe008e2d2de74b213716c

**Comment by gka** [comment]
alright, I did my best to rebase. Almost all the conflicts where with build files in `www/static/js/svelte/...` which I always resolved "using ours". After I was done I ran `npm install` again and then re-build the visualize step again using `ROLLUP_TGT_APP=visualize make svelte-all`. Hope everything still works.

**Comment by gka** [comment]
I tested if briefly on localhost with `d3-bars` controls and it seems to work

**Comment by gka** [comment]
i think `www/static/js/dw/chart/visualize.js` was only jsprettier

**Pull request merged**
