### PR TITLE
Migrate after dataset

### PR DESCRIPTION
**Pull request by elanals**
Possible solution for a problem in a migration for table column settings. See [this PR](https://github.com/datawrapper/plugin-tables/pull/37).

### CODE REVIEW

**Comment by elanals** [comment]
The table PR needs to be merged so that Gregor can start working on the heatmaps, and this is still the only missing piece. Are there any reasons not to change where the migration happens here too?

**Comment by gka** [comment]
the only thing that comes to my mind is that we need to test this thoroughly. So far the dataset-migration has only been used in `d3-maps`, and since this PR would bring this change to all visualizations with svelte controls we should make sure that they all work as expected.

**Comment by davidkokkelink** [comment]
I can test some scenarios and if everything's fine we can merge later today

**Comment by gka** [comment]
thanks

**Review by davidkokkelink — APPROVED** [review]
looks good :+1:

**Comment by davidkokkelink** [comment]
resolved with svelte visualize

**Pull request closed without merging**
