### PR TITLE
Catch font loading errors

### PR DESCRIPTION
**Pull request by davidkokkelink**
To get rid of these types of errors that plague our users' consoles:
timeout

### CODE REVIEW

**Comment by davidkokkelink** [comment]
linter hates me for this because i don't "handle the error object". maybe @sto3psl has some insight on the best way to fix this?

**Comment by sto3psl** [comment]
@davidkokkelink hmm I think you could print something with `console.warn`.

Maybe `console.warn('Font observer timed out.')` or something. Otherwise an `//eslint-disable-line` can help too 😄

**Comment by davidkokkelink** [comment]
i don't want to log, so i went with `// eslint-disable-next-line`

**Comment by davidkokkelink** [comment]
you're right, changed it

**Pull request merged**
