### PR TITLE
add fields for tracking when and by whom a user was invited to a team

### PR DESCRIPTION
**Pull request by gka**
see also https://github.com/datawrapper/orm/pull/14 for orm schema update
* adds two new fields `user_organization.invited_by` and `user_organization.invited_at`.
* fills in default values for existing team members, assuming..
   * each team member was invited by whoever is owner _now_
   * each team member was invited by the time either the team or the user was created (whichever happened last)

### CODE REVIEW

**Comment by davidkokkelink** [comment]
looks good to me

**Comment by davidkokkelink** [comment]
the db migration didn't run through successfully on my instance (it only added `invited_by` but not `invited_at`). i tried running it manually and got this error:
sql-error

**Comment by gka** [comment]
ah my bad. need to allow NULL until the `invited_at` dates have been filled in

**Comment by gka** [comment]
should run through now

**Comment by davidkokkelink** [comment]
yes, works now :+1:

**Pull request merged**
