### PR TITLE
Remove obsolete php, twig & js code

### PR DESCRIPTION
**Pull request by gka**
This PR removes a lot of obsolete code.

The following files were **edited**:

* `controller/chart/preview.php`
  removed the old code chart preview controller code (was already commeted out)
* `controller/chart/publish.php` & `controller/edit.php`
   the old and new publish controllers now load the embed codes from our new API
* `lib/api/charts.php`
   removed the old `charts/:id/publish` and `charts/:id/publish/status` routes, along with two other routes that were already obsolete before the node publishing
* `lib/core/build/classes/datawrapper/Chart.php`
   removed the `Chart::publish` & `Chart::generateEmbedCodes` ORM functions. Among other things this function used to generate the embed codes, which we now implemented in the Node publishing
* `lib/utils/check_server.php`
* `src/rollup.config.js`

The following files were **deleted** entirely:
* `lib/utils/chart_content.php`
* `lib/utils/chart_publish.php`
* `src/embed/index.js`
   This file has been moved to [chart-core](https://github.com/datawrapper/chart-core/pull/16)
* `templates/chart-styles.less.twig`
    Replaced by [styles.less](https://github.com/datawrapper/chart-core/blob/master/lib/styles.less) in chart-core
* `templates/chart.twig`
   Replaced by [Chart.svelte](https://github.com/datawrapper/chart-core/blob/master/lib/Chart.svelte) in chart-core
* 'src/render/index.js` and `templates/chart/render.js.twig`
   Replaced by [render.js](https://github.com/datawrapper/chart-core/blob/master/lib/render.js) in chart-core
* `www/static/js/dw/chart.base.js`
    Replaced by [Chart.svelte](https://github.com/datawrapper/chart-core/blob/master/lib/Chart.svelte) in chart-core
* `www/static/js/dw/chart/visualize/liveUpdate.js`

### CODE REVIEW

**Comment by davidkokkelink** [comment]
one of my favorite PRs in datawrapper history! I also removed:
- `Chart.redirectPreviousVersions`
- `Chart.unpublish`
- `Chart.plainUrl`
- `Chart.assetUrl`
- `Chart.getCDNPath`
- `Chart.getCaption`

**Comment by davidkokkelink** [comment]
also: replaced `controller/embed.php` with a redirect to the `?published=1` version of the new frontend. which in turn allowed me to remove `check_iframe_origin` from the codebase

**Comment by davidkokkelink** [comment]
also gone: the hooks `PUBLISH_FILES, UNPUBLISH_FILES, GET_PUBLISHED_URL, GET_ASSET_DOMAIN, GET_PUBLISH_STORAGE_KEY`

**Comment by davidkokkelink** [comment]
also gone: unused old API endpoints (`/charts/:id/vis-data`, `/gallery`), also cleaned up some stuff in plugin `signin`

**Comment by gka** [comment]
is this good to be merged now? it worked for me after checking out the `onetime-access` plugin branch

**Comment by davidkokkelink** [comment]
good to be merged imo

**Pull request merged**
