### PR TITLE
Add margin to alternative signin links

### PR DESCRIPTION
**Pull request by ilokhov**
The new sign in view is a nice improvement compared to the previous version. I noticed one detail that could be improved further though: there are currently no margins between the alternative sign in links. This PR adds these margins.

Before:

Screenshot 2020-01-23 at 13 03 28

After:

Screenshot 2020-01-23 at 13 04 41

### CODE REVIEW

**Comment by elanals** [comment]
Just noticed that it doesn't look like these changes were pushed live? @ilokhov @gka 
image

**Comment by gka** [comment]
now they are

**Comment by elanals** [comment]
Nice

**Comment by ilokhov** [comment]
Sorry, I didn't get around to deploying this...

**Pull request merged**
