### PR TITLE
quick copy embed code feature

### PR DESCRIPTION
**Pull request by gka**

### CODE REVIEW

**Comment by elanals** [comment]
No screenshot? Am I supposed to check out the branch? :D

**Comment by elanals** [comment]
Also wow that was fast, thank you!

**Comment by davidkokkelink** [comment]
This PR uses ES6 features in non-rolluped code, which would probably break in certain browsers. Also there's a console log that probably isn't needed in production.

**Comment by gka** [comment]
@davidkokkelink you're talking about the two `const` statements, right? I'll replace them with `var`. the rest should run in IE9

**Comment by gka** [comment]
I deployed it on staging

**Comment by davidkokkelink** [comment]
Thanks! Should be good now

**Comment by gka** [comment]
tested it on IE11 and it worked. can''t test on IE10 because login is broken

**Comment by davidkokkelink** [comment]
Great - I noticed there's a translation missing for "copied to clipboard"

**Comment by gka** [comment]
none of the 3 buttons is translated on production.

**Comment by gka** [comment]
I am closing this for now. We can re-open the PR once we're done with the node publishing so you can properly review this.

**Pull request closed without merging**
